project: wasabi-engine
version: 0.0.1
stovetop:
  variables:
    SRC: src
    OUT: bin
    CFLAGS: -Wall -Wextra -O2
    ENGINE: src/engine/engine.c
    ECS: src/ecs/ecs_entity.c src/ecs/ecs_position.c src/ecs/ecs_velocity.c src/ecs/ecs.c
    GAME: src/game/game.c
    UTIL: src/util/log.c
    MAIN: src/main.c
    DIR: /home/yeskonerism/programming/c/wasabi-engine
  runtime:
    type: gcc
    version: 
  commands:
    build: ${CFLAGS} ${ENGINE} ${ECS} ${GAME} ${UTIL} ${MAIN} -I${DIR}/${SRC} -o ${OUT}/wasabi-engine
    run: 
    executable: bin/wasabi-engine
    test: 
    clean: rm -rf ${OUT}
    deploy: 
  aliases:
    all: stove b -nh && stove r -s -nh
  hooks: 
  profiles: 
